name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#           ARGS: "-avz --delete"
#           SOURCE: "out/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          SCRIPT_AFTER: |
            # fix nvm command not found
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm --help
            #--------------------------
            nvm use 16
            node -v
            cd /var/www/html/test/nextjs-github-actions-test
            git pull
            yarn
            yarn build
            pm2 restart nextjs-github-actions-test
            
#           TARGET: "/var/www/html/test"
