name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#           ARGS: "-avz --delete"
#           SOURCE: "out/"
          REMOTE_HOST: 133.130.102.247
          REMOTE_USER: root
          REMOTE_PORT: 2223
          SCRIPT_AFTER: |
            exec bash
            source $HOME/.bashrc #fix nvm command is not found
            echo $0
            node -v
            nvm use 16
            node -v
            cd /var/www/html/test/nextjs-github-actions-test
            git pull
            yarn
            yarn build
            pm2 restart nextjs-github-actions-test
            
#           TARGET: "/var/www/html/test"
